version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: eventia_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: eventia_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    container_name: eventia_redis
    ports:
      - "6379:6379"

volumes:
  mysql_data: